// Generated by CoffeeScript 1.9.1
(function() {
  var Component,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = Component = (function(superClass) {
    extend(Component, superClass);

    function Component() {
      return Component.__super__.constructor.apply(this, arguments);
    }

    Component.contextTypes = {
      shared: React.PropTypes.any
    };

    Component.prototype.dispatch = function() {
      var ref;
      return (ref = this.context.shared).emit.apply(ref, arguments);
    };

    Component.prototype.createChildRouter = function(node) {
      var DefaultLayout, Router, childRouter;
      Router = require('./router');
      DefaultLayout = require('./default-layout');
      childRouter = new Router(DefaultLayout, node);
      return childRouter;
    };

    Component.prototype.createContextOnNode = function(node, contextClass, props) {
      var childRouter;
      childRouter = this.createChildRouter(node);
      return childRouter.pushContext(contextClass, props).then((function(_this) {
        return function(context) {
          return Promise.resolve(context);
        };
      })(this));
    };

    return Component;

  })(React.Component);

}).call(this);
