// Generated by CoffeeScript 1.9.1
(function() {
  var Context, EventEmitter,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  EventEmitter = require('./event-emitter');

  module.exports = Context = (function(superClass) {
    extend(Context, superClass);

    function Context(_component, props1) {
      var ref, subscribers;
      this._component = _component;
      this.props = props1;
      Context.__super__.constructor.apply(this, arguments);
      subscribers = (ref = this.constructor.subscribers) != null ? ref : [];
      this._onDisposes = [];
      this.lifecycle = null;
      this.delegate((function(_this) {
        return function(eventName, callback) {
          if (callback != null) {
            return _this.on(eventName, callback);
          } else {
            if (typeof Rx === "undefined" || Rx === null) {
              throw new Error('you need callback as second argument if you don\'t have Rx');
            }
            return Rx.Node.fromEvent(_this, eventName);
          }
        };
      })(this));
    }

    Context.prototype.dispose = function() {
      return Promise.all(this._onDisposes);
    };

    Context.prototype.getActiveComponent = function() {
      return this._component.refs.root;
    };

    Context.prototype.delegate = function(subscribe) {
      var ref, subscribers;
      subscribers = (ref = this.constructor.subscribers) != null ? ref : [];
      return subscribers.forEach((function(_this) {
        return function(subscriber) {
          return subscriber(_this, subscribe);
        };
      })(this));
    };

    Context.prototype.update = function(stateFn) {
      if (stateFn == null) {
        stateFn = null;
      }
      return Promise.resolve((this.state == null) && this.props ? Promise.resolve(this.initState(this.props)).then((function(_this) {
        return function(state1) {
          _this.state = state1;
          return Promise.resolve();
        };
      })(this)) : void 0).then((function(_this) {
        return function() {
          var nextState, ref;
          nextState = (ref = typeof stateFn === "function" ? stateFn(_this.state) : void 0) != null ? ref : _this.state;
          if (nextState != null) {
            _this.state = nextState;
          }
          return _this.expandComponentProps(_this.props, _this.state);
        };
      })(this)).then((function(_this) {
        return function(templateProps) {
          return _this._component.setState({
            activeContext: _this,
            templateProps: templateProps
          });
        };
      })(this));
    };

    Context.prototype.initState = function(props) {
      return props;
    };

    Context.prototype.expandComponentProps = function(props, state) {
      return props;
    };

    Context.prototype.render = function(templateProps) {
      var component;
      if (templateProps == null) {
        templateProps = {};
      }
      component = React.createFactory(this.constructor.component);
      return component(templateProps);
    };

    Context.prototype._initByProps = function(props1) {
      this.props = props1;
      return new Promise((function(_this) {
        return function(done) {
          return Promise.resolve(_this.initState(_this.props)).then(function(state1) {
            _this.state = state1;
            return done();
          });
        };
      })(this));
    };

    return Context;

  })(EventEmitter);

}).call(this);
