// Generated by CoffeeScript 1.8.0
(function() {
  var Component, T;

  Component = require('./component');

  T = React.PropTypes;

  module.exports = React.createClass({
    childContextTypes: {
      shared: T.any
    },
    getChildContext: function() {
      return {
        shared: this.state.activeContext
      };
    },
    getInitialState: function() {
      return {
        activeContext: null,
        templateProps: {}
      };
    },
    render: function() {
      var _ref;
      if (this.state.activeContext != null) {
        return React.createFactory((_ref = this.state.activeContext) != null ? _ref.constructor.component : void 0)(this.state.templateProps);
      } else {
        return React.createElement('div');
      }
    }
  });

}).call(this);
