// Generated by CoffeeScript 1.8.0
(function() {
  var Arda;

  module.exports = Arda = {};

  Arda.Component = require('./component');

  Arda.Context = require('./context');

  Arda.DefaultLayout = require('./default-layout');

  Arda.Router = require('./router');

  Arda.mixin = require('./mixin');

  Arda.subscriber = function(id) {
    return id;
  };

}).call(this);
